---
title: "Covid_Luminex"
date: "07/06/2022"
output: 
  html_document:
    code_folding: hide
    toc: yes
    theme: spacelab
  pdf_document: default
---

```{r setup, include=FALSE}
library(dplyr)  
library(data.table)
library(ggplot2)
library(reshape2)
library(gplots)
library(pheatmap)
library(magrittr)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(data.table)
library(RColorBrewer)
library(reshape)
library(limma)
library(sva)
library(ggdendro)
```

#Load luminex data for all exps
```{r}
#file with mac luminex data
data_mac<-fread("~/Luminex/Plate1.csv",header=T)
data_mac<-as.data.frame(data_mac)

dim(data_mac)

#Create vector containing cytokine names
name <- (names(data_mac[,7:54]))

#Normalzie data
norm_data_mac <- data_mac
norm_data_mac[name] <- log(norm_data_mac[name]+1)

#file with foamcells luminex data
data_foam<-fread("~/Luminex/Plate2.csv",header=T)
data_foam<-as.data.frame(data_foam)

dim(data_foam)

#Create vector containing cytokine names
name <- (names(data_foam[,7:54]))

#Normalzie data
norm_data_foam <- data_foam
norm_data_foam[name] <- log(norm_data_foam[name]+1)

#file with plaque luminex data
data_mac_plaque<-fread("~/Luminex/Plate3.csv",header=T)
data_mac_plaque<-as.data.frame(data_mac_plaque)

dim(data_mac_plaque)

#Create vector containing cytokine names
name <- (names(data_mac_plaque[,8:55]))

#Normalzie data
data_mac_plaque <- data_mac_plaque
data_mac_plaque[name] <- log(data_mac_plaque[name]+1)

```

## Infected vs not-infected in Macrophages
```{r}
####Infected vs not-infected 
norm_data_mac_zero<-norm_data_mac[which(norm_data_mac$Timepoint == "0"),]
norm_data_mac_two<-norm_data_mac[which(norm_data_mac$Timepoint == "2"),]
norm_data_mac_eight<-norm_data_mac[which(norm_data_mac$Timepoint == "8"),]
norm_data_mac_24<-norm_data_mac[which(norm_data_mac$Timepoint == "24"),]
norm_data_mac_48<-norm_data_mac[which(norm_data_mac$Timepoint == "48"),]

#function to test between timepoint using pairwise comparison 
zero_ttest = lapply(name, function(cyto) {

	idx1 = norm_data_mac_zero$`Virus status` == "Infected"
	idx2 = norm_data_mac_zero$`Virus status` == "Not infected"

	x = norm_data_mac_zero[idx1, cyto]
	y = norm_data_mac_zero[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(zero_ttest) = name

#function to test between timepoint using pairwise comparison 
two_ttest = lapply(name, function(cyto) {

	idx1 = norm_data_mac_two$`Virus status` == "Infected"
	idx2 = norm_data_mac_two$`Virus status` == "Not infected"

	x = norm_data_mac_two[idx1, cyto]
	y = norm_data_mac_two[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(two_ttest) = name

eight_ttest = lapply(name, function(cyto) {

	idx1 = norm_data_mac_eight$`Virus status` == "Infected"
	idx2 = norm_data_mac_eight$`Virus status` == "Not infected"

	x = norm_data_mac_eight[idx1, cyto]
	y = norm_data_mac_eight[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(eight_ttest) = name


twentyfour_ttest = lapply(name, function(cyto) {

	idx1 = norm_data_mac_24$`Virus status` == "Infected"
	idx2 = norm_data_mac_24$`Virus status` == "Not infected"

	x = norm_data_mac_24[idx1, cyto]
	y = norm_data_mac_24[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(twentyfour_ttest) = name

forty8_ttest = lapply(name, function(cyto) {

	idx1 = norm_data_mac_48$`Virus status` == "Infected"
	idx2 = norm_data_mac_48$`Virus status` == "Not infected"

	x = norm_data_mac_48[idx1, cyto]
	y = norm_data_mac_48[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(forty8_ttest) = name

pvals = data.frame(
	zero=sapply(zero_ttest, function(x) x$p.value),
	two=sapply(two_ttest, function(x) x$p.value),
	eight=sapply(eight_ttest, function(x) x$p.value),
	twentyfour=sapply(twentyfour_ttest, function(x) x$p.value),
	fortyeight=sapply(forty8_ttest, function(x) x$p.value)
)
pvals[is.na(pvals)] = 1.0  # conservative for missing p-values

p.adjust.M <- p.adjust.methods[p.adjust.methods =="BH"]

pvals_BH = data.frame(
	zero=sapply(p.adjust.M, function(x) p.adjust(pvals$zero, x)),
	two=sapply(p.adjust.M, function(x) p.adjust(pvals$two, x)),
	eight=sapply(p.adjust.M, function(x) p.adjust(pvals$eight, x)),
	twentyfour=sapply(p.adjust.M, function(x) p.adjust(pvals$twentyfour, x)),
	fortyeight=sapply(p.adjust.M, function(x) p.adjust(pvals$fortyeight, x))
)

colnames(pvals_BH)<-c("zero","two","eight","twentyfour","fortyeight")
pvals_BH[is.na(pvals_BH)] = 1.0  # conservative for missing p-values

  
fold_changes = data.frame(
	zero=sapply(zero_ttest, function(x) log2(x$estimate[1] / x$estimate[2])),
	two=sapply(two_ttest, function(x) log2(x$estimate[1] / x$estimate[2])),
	eight=sapply(eight_ttest, function(x) log2(x$estimate[1] / x$estimate[2])),
	twentyfour=sapply(twentyfour_ttest, function(x) log2(x$estimate[1] / x$estimate[2])),
	fortyeight=sapply(forty8_ttest, function(x) log2(x$estimate[1] / x$estimate[2]))
)
rownames(fold_changes) = name
fold_changes[is.na(fold_changes)] = 0.0
fold_changes[fold_changes > 10] = 10
fold_changes[fold_changes < -10] = -10

mat_mac_inf_not_fold = fold_changes
mat_mac_inf_not_fold = data.matrix(mat_mac_inf_not_fold)

noted = matrix("", nrow=nrow(mat_mac_inf_not_fold), ncol=ncol(mat_mac_inf_not_fold))
noted[pvals_BH < 0.1] = " "
noted[pvals_BH < 0.05] = "(*)"
noted[pvals_BH < 0.01] = "(**)"
noted[pvals_BH < 0.001] = "(***)"

notes[pvals < 0.1] = " "
notes[pvals < 0.05] = "*"
notes[pvals < 0.01] = "**"
notes[pvals < 0.001] = "***"

pdf("/mac_infec_notinfect_fold_change_pvalue_BH_ordered.pdf", width=10,height=12)
heatmap.2(mat_mac,
	Colv=FALSE,
	Rowv=FALSE,
	mar=c(8, 14),
	trace="none",
	breaks=seq(-0.5, 0.5, length.out=101),
	col=colorRampPalette(rev(brewer.pal(9, "Spectral")))(100),
	key.xlab=expression("Infected/Not infected"("log"[2] * " FC")), key.ylab=NA,
	key.title="", 
	cellnote=notes_f,
	notecol="black",
	cexCol=1.0
)
dev.off()

```


##Infected vs not-infected in foam cells
```{r}
norm_data_foam_zero<-norm_data_foam[which(norm_data_foam$Timepoint == "0"),]
norm_data_foam_two<-norm_data_foam[which(norm_data_foam$Timepoint == "2"),]
norm_data_foam_eight<-norm_data_foam[which(norm_data_foam$Timepoint == "8"),]
norm_data_foam_24<-norm_data_foam[which(norm_data_foam$Timepoint == "24"),]
norm_data_foam_48<-norm_data_foam[which(norm_data_foam$Timepoint == "48"),]

#function to test between timepoint using pairwise comparison 
zero_ttest = lapply(name, function(cyto) {

	idx1 = norm_data_foam_zero$`Virus status` == "Infected"
	idx2 = norm_data_foam_zero$`Virus status` == "Not infected"

	x = norm_data_foam_zero[idx1, cyto]
	y = norm_data_foam_zero[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(zero_ttest) = name

#function to test between timepoint using pairwise comparison 
two_ttest = lapply(name, function(cyto) {

	idx1 = norm_data_foam_two$`Virus status` == "Infected"
	idx2 = norm_data_foam_two$`Virus status` == "Not infected"

	x = norm_data_foam_two[idx1, cyto]
	y = norm_data_foam_two[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(two_ttest) = name

eight_ttest = lapply(name, function(cyto) {

	idx1 = norm_data_foam_eight$`Virus status` == "Infected"
	idx2 = norm_data_foam_eight$`Virus status` == "Not infected"

	x = norm_data_foam_eight[idx1, cyto]
	y = norm_data_foam_eight[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(eight_ttest) = name


twentyfour_ttest = lapply(name, function(cyto) {

	idx1 = norm_data_foam_24$`Virus status` == "Infected"
	idx2 = norm_data_foam_24$`Virus status` == "Not infected"

	x = norm_data_foam_24[idx1, cyto]
	y = norm_data_foam_24[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(twentyfour_ttest) = name

forty8_ttest = lapply(name, function(cyto) {

	idx1 = norm_data_foam_48$`Virus status` == "Infected"
	idx2 = norm_data_foam_48$`Virus status` == "Not infected"

	x = norm_data_foam_48[idx1, cyto]
	y = norm_data_foam_48[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(forty8_ttest) = name

pvals = data.frame(
	zero=sapply(zero_ttest, function(x) x$p.value),
	two=sapply(two_ttest, function(x) x$p.value),
	eight=sapply(eight_ttest, function(x) x$p.value),
	twentyfour=sapply(twentyfour_ttest, function(x) x$p.value),
	fortyeight=sapply(forty8_ttest, function(x) x$p.value)
)
pvals[is.na(pvals)] = 1.0  # conservative for missing p-values

p.adjust.M <- p.adjust.methods[p.adjust.methods =="BH"]

pvals_BH = data.frame(
	zero=sapply(p.adjust.M, function(x) p.adjust(pvals$zero, x)),
	two=sapply(p.adjust.M, function(x) p.adjust(pvals$two, x)),
	eight=sapply(p.adjust.M, function(x) p.adjust(pvals$eight, x)),
	twentyfour=sapply(p.adjust.M, function(x) p.adjust(pvals$twentyfour, x)),
	fortyeight=sapply(p.adjust.M, function(x) p.adjust(pvals$fortyeight, x))
)

fold_changes = data.frame(
	zero=sapply(zero_ttest, function(x) log2(x$estimate[1] / x$estimate[2])),
	two=sapply(two_ttest, function(x) log2(x$estimate[1] / x$estimate[2])),
	eight=sapply(eight_ttest, function(x) log2(x$estimate[1] / x$estimate[2])),
	twentyfour=sapply(twentyfour_ttest, function(x) log2(x$estimate[1] / x$estimate[2])),
	fortyeight=sapply(forty8_ttest, function(x) log2(x$estimate[1] / x$estimate[2]))
)
rownames(fold_changes) = name
fold_changes[is.na(fold_changes)] = 0.0
fold_changes[fold_changes > 10] = 10
fold_changes[fold_changes < -10] = -10

mat_foam_inf_not_fold = fold_changes
mat_foam_inf_not_fold = data.matrix(mat_foam_inf_not_fold)

noted = matrix("", nrow=nrow(mat_foam_inf_not_fold ), ncol=ncol(mat_foam_inf_not_fold ))
noted[pvals_BH < 0.1] = " "
noted[pvals_BH < 0.05] = "(*)"
noted[pvals_BH < 0.01] = "(**)"
noted[pvals_BH < 0.001] = "(***)"

notes[pvals < 0.1] = " "
notes[pvals < 0.05] = "*"
notes[pvals < 0.01] = "**"
notes[pvals < 0.001] = "***"


pdf("foam_infec_notinfect_fold_change_pvalue_BH_ordered.pdf", width=8,height=12)
heatmap.2(mat_foam,
	Colv=FALSE,
	Rowv=FALSE,
	mar=c(8, 14),
	trace="none",
	breaks=seq(-0.5, 0.5, length.out=101),
	col=colorRampPalette(rev(brewer.pal(9, "Spectral")))(100),
	key.xlab=expression("Infected/Not infected" ("log"[2] * "FC")), key.ylab=NA,
	key.title="",
	cellnote=notes_f,
	notecol="black",
	cexCol=1.0
)
dev.off()
```


## Plate3
## Infected vs not-infected
```{r}
# Cytokine data
# Plaque batch correction
plaque<-data_mac_plaque[,8:ncol(data_mac_plaque)]
plaque_info<-data_mac_plaque[,2:7]
plaque_batch = t(ComBat(t(plaque), batch=factor(plaque_info$Experiment)))

plaque_batch_comb<-cbind(plaque_info,plaque_batch)

#Create vector containing cytokine names
name <- (names(plaque_batch_comb[,7:54]))
plaque_batch_norm<-as.data.frame(plaque_batch_comb)

#Normalize data
plaque_batch_norm[name] <- log(plaque_batch_norm[name]+1)


data_mac_plaque_nrp<-data_mac_plaque[which(data_mac_plaque$Treatment != "NRP1"),]
data_mac_plaque_donor1<-data_mac_plaque_nrp[which(data_mac_plaque_nrp$Donor != "1"),]
data_mac_plaque_donor<-data_mac_plaque_donor1[which(data_mac_plaque_donor1$Donor != "pooled"),]

data_mac_plaque_zero<-data_mac_plaque_donor[which(data_mac_plaque_donor$Timepoint == "0"),]
data_mac_plaque_24<-data_mac_plaque_donor[which(data_mac_plaque_donor$Timepoint == "24"),]
data_mac_plaque_48<-data_mac_plaque_donor[which(data_mac_plaque_donor$Timepoint == "48"),]
data_mac_plaque_72<-data_mac_plaque_donor[which(data_mac_plaque_donor$Timepoint == "72"),]

#function to test between timepoint using pairwise comparison 
zero_ttest = lapply(name, function(cyto) {

	idx1 = data_mac_plaque_zero$`Virus status` == "Infected"
	idx2 = data_mac_plaque_zero$`Virus status` == "Not infected"

	x = data_mac_plaque_zero[idx1, cyto]
	y = data_mac_plaque_zero[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=TRUE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(zero_ttest) = name

twentyfour_ttest = lapply(name, function(cyto) {

	idx1 = data_mac_plaque_24$`Virus status` == "Infected"
	idx2 = data_mac_plaque_24$`Virus status` == "Not infected"

	x = data_mac_plaque_24[idx1, cyto]
	y = data_mac_plaque_24[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	
	try({
		result = t.test(x, y, paried=TRUE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(twentyfour_ttest) = name

forty8_ttest = lapply(name, function(cyto) {

	idx1 = data_mac_plaque_48$`Virus status` == "Infected"
	idx2 = data_mac_plaque_48$`Virus status` == "Not infected"

	x = data_mac_plaque_48[idx1, cyto]
	y = data_mac_plaque_48[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=TRUE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(forty8_ttest) = name

seventytwo_ttest = lapply(name, function(cyto) {

	idx1 = data_mac_plaque_72$`Virus status` == "Infected"
	idx2 = data_mac_plaque_72$`Virus status` == "Not infected"

	x = data_mac_plaque_72[idx1, cyto]
	y = data_mac_plaque_72[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=TRUE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(seventytwo_ttest) = name


pvals = data.frame(
	twentyfour=sapply(twentyfour_ttest, function(x) x$p.value),
	fortyeight=sapply(forty8_ttest, function(x) x$p.value),
	seventytwo=sapply(seventytwo_ttest, function(x) x$p.value)
)
pvals[is.na(pvals)] = 1.0  # conservative for missing p-values

p.adjust.M <- p.adjust.methods[p.adjust.methods =="BH"]

pvals_BH = data.frame(
	twentyfour=sapply(p.adjust.M, function(x) p.adjust(pvals$twentyfour, x)),
	fortyeight=sapply(p.adjust.M, function(x) p.adjust(pvals$fortyeight, x)),
	seventytwo=sapply(p.adjust.M, function(x) p.adjust(pvals$seventytwo, x))
)

fold_changes = data.frame(
	twentyfour=sapply(twentyfour_ttest, function(x) log2(x$estimate[1] / x$estimate[2])),
	fortyeight=sapply(forty8_ttest, function(x) log2(x$estimate[1] / x$estimate[2])),
	seventytwo=sapply(seventytwo_ttest, function(x) log2(x$estimate[1] / x$estimate[2]))
)

rownames(fold_changes) = name
fold_changes[is.na(fold_changes)] = 0.0
fold_changes[fold_changes > 10] = 10
fold_changes[fold_changes < -10] = -10

data_mac_plaque_fold = fold_changes 
data_mac_plaque_fold = data.matrix(data_mac_plaque_fold)

noted = matrix("", nrow=nrow(data_mac_plaque_fold), ncol=ncol(data_mac_plaque_fold))
noted[pvals_BH < 0.1] = " "
noted[pvals_BH < 0.05] = "(*)"
noted[pvals_BH < 0.01] = "(**)"
noted[pvals_BH < 0.001] = "(***)"

notes[pvals < 0.1] = " "
notes[pvals < 0.05] = "*"
notes[pvals < 0.01] = "**"
notes[pvals < 0.001] = "***"

pdf("mac_plaque_infec_notinfect_fold_change_pvalue_BH_ordered_donor_removed_paired.pdf", width=8,height=12)
heatmap.2(mat_plaque,
	Colv=FALSE,
	Rowv=FALSE,
	mar=c(8, 14),
	trace="none",
	breaks=seq(-0.5, 0.5, length.out=101),
	col=colorRampPalette(rev(brewer.pal(9, "Spectral")))(100),
	key.xlab=expression("Infected/Not infected" ("log"[2] * "FC")), key.ylab=NA,
	key.title="",
	cellnote=notes_f,
	notecol="black",
	cexCol=1.0
)
dev.off()
```

## Plaque vs Margin at timepoint 48H & 72H separately 
```{r}
data_mac_plaque_not<-data_mac_plaque_nrp[which(data_mac_plaque_nrp$`Virus status` != "Not infected"),]
data_mac_plaque_1<-data_mac_plaque_not[which(data_mac_plaque_not$Donor != "1"),]
data_mac_plaque_2<-data_mac_plaque_1[which(data_mac_plaque_1$Donor != "2"),]
data_mac_plaque_3<-data_mac_plaque_2[which(data_mac_plaque_2$Donor != "3"),]

data_mac_plaque_time48<-data_mac_plaque_3[which(data_mac_plaque_3$Timepoint=="48"),]
data_mac_plaque_time72<-data_mac_plaque_3[which(data_mac_plaque_3$Timepoint=="72"),]


#function to test between timepoint using pairwise comparison 
plaque_margin_time48_ttest = lapply(name, function(cyto) {

	idx1 = data_mac_plaque_time48$`Sample type` == "Plaque"
	idx2 = data_mac_plaque_time48$`Sample type` == "Margin"

	x = data_mac_plaque_time48[idx1, cyto]
	y = data_mac_plaque_time48[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(plaque_margin_time48_ttest) = name

pvals = data.frame(
	plaque_time48_margin=sapply(plaque_margin_time48_ttest, function(x) x$p.value))

p.adjust.M <- p.adjust.methods[p.adjust.methods =="BH"]

pvals_BH = data.frame(
	plaque_time48_margin=sapply(p.adjust.M, function(x) p.adjust(pvals$plaque_time48_margin, x))
)

fold_changes = data.frame(
	plaque_time48_margin=sapply(plaque_margin_time48_ttest, function(x) log2(x$estimate[1] / x$estimate[2]))
)

rownames(fold_changes) = name
fold_changes[is.na(fold_changes)] = 0.0
fold_changes[fold_changes > 10] = 10
fold_changes[fold_changes < -10] = -10

data_mac_plaque_margin_fold = fold_changes 
data_mac_plaque_margin_fold = data.matrix(data_mac_plaque_margin_fold)

dot<-cbind(pvals,pvals_BH,fold_changes)
dot$group<-"Infected - Plaque_vs_Margin at Timepoint 48H"
colnames(dot)<-c("pvalue","BH","log2(FC)","group")

dot$type_pvalue <- ifelse(dot$BH < 0.05, "Significant","Not Significant")
dot$type_pvalue <- factor(dot$type_pvalue, levels = c("Significant","Not Significant"))

# Timepoint 72H
#function to test between timepoint using pairwise comparison 
plaque_margin_time72_ttest = lapply(name, function(cyto) {

	idx1 = data_mac_plaque_time72$`Sample type` == "Plaque"
	idx2 = data_mac_plaque_time72$`Sample type` == "Margin"

	x = data_mac_plaque_time72[idx1, cyto]
	y = data_mac_plaque_time72[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(plaque_margin_time72_ttest) = name

pvals = data.frame(
	plaque_time72_margin=sapply(plaque_margin_time72_ttest, function(x) x$p.value)
)
p.adjust.M <- p.adjust.methods[p.adjust.methods =="BH"]

pvals_BH = data.frame(
	plaque_time72_margin=sapply(p.adjust.M, function(x) p.adjust(pvals$plaque_time72_margin, x))
)

fold_changes = data.frame(
	plaque_time72_margin=sapply(plaque_margin_time72_ttest, function(x) log2(x$estimate[1] / x$estimate[2]))
)

rownames(fold_changes) = name
fold_changes[is.na(fold_changes)] = 0.0
fold_changes[fold_changes > 10] = 10
fold_changes[fold_changes < -10] = -10

data_mac_plaque_margin_fold = fold_changes 
data_mac_plaque_margin_fold = data.matrix(data_mac_plaque_margin_fold)

dot_not<-cbind(pvals,pvals_BH,fold_changes)
dot_not$group<-"Infected - Plaque_vs_Margin at Timepoint 72H"
colnames(dot_not)<-c("pvalue","BH","log2(FC)","group")

dot_not$type_pvalue <- ifelse(dot_not$BH < 0.05, "Significant","Not Significant")
dot_not$type_pvalue <- factor(dot_not$type_pvalue, levels = c("Significant","Not Significant"))

dot_final<-merge(dot,dot_not)

pdf(file="point_plot_plaque_margin_48_72H.pdf",height = 10,width = 8)
ggplot(dot_final, aes(group, dot_final$X)) +
  geom_point(aes(fill = log2.FC., size = -log10(BH), color = type_pvalue, shape = type_pvalue)) + 
  scale_fill_gradientn(colours = colorRampPalette(c("#3d67a3", "white","#ce1020"))(99),
  limits = c(-2,2), breaks = c(-2.0, -1.0, 0, 1.0, 2.0)) +
  scale_shape_manual(values = c(23,21)) +
  scale_color_manual(values = c("black","grey50","black"))+#, "grey50")) +
  scale_size_continuous(breaks=c(0.5,1.5,2.5), range=c(1,4)) +
  theme_dendro() +
  theme(plot.margin = margin(1, 1, 1, 1, "cm")) +
  coord_fixed(ratio = 0.7) +
  labs(fill = "Log2 (Fold change)", size = "-Log10 (adj p value)", color = "", shape = "") +
  theme(axis.text.x = element_text(size = 10, face = "plain", colour = "black", angle = 60,vjust = 1.1, hjust=1.1),axis.text.y = element_text(size = 10, face = "plain", colour = "black")) +
  theme(legend.text = element_text(size = 10, face = "plain", colour = "black"), 
        legend.title = element_text(size = 10, face = "plain", colour = "black"), 
        legend.key.height = unit(0.5, "cm"), legend.key.width = unit(0.3, "cm"))   
dev.off()
```


## NRP1 vs Not treated in plaque
```{r}
# NRP1 vs Not
data_mac_plaque_infect<-data_mac_plaque[which(data_mac_plaque$`Virus status` != "Not infected"),]

#function to test between nrp1 vs not treated
nrp1_ttest = lapply(name, function(cyto) {

	idx1 = data_mac_plaque_infect$Treatment == "NRP1" & data_mac_plaque_infect$`Sample type` == "Plaque"
	idx2 = data_mac_plaque_infect$Treatment == "Not treated" &  data_mac_plaque_infect$`Sample type` == "Plaque"

	x = data_mac_plaque_infect[idx1, cyto]
	y = data_mac_plaque_infect[idx2, cyto]

	x[x < 0] = 0
	y[y < 0] = 0

	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return(list(p.value=1.0, estimate=c(0, 0)))
})
names(nrp1_ttest) = name

pvals = data.frame(
	nrp1=sapply(nrp1_ttest, function(x) x$p.value)
)

p.adjust.M <- p.adjust.methods[p.adjust.methods =="BH"]

pvals_BH = data.frame(
	nrp1=sapply(p.adjust.M, function(x) p.adjust(pvals$nrp1, x))
)

fold_changes = data.frame(
	nrp1=sapply(nrp1_ttest, function(x) log2(x$estimate[1] / x$estimate[2]))
)

rownames(fold_changes) = name

data_mac_nrp1_fold = fold_changes 
data_mac_nrp1_fold = data.matrix(data_mac_nrp1_fold)

dot<-cbind(pvals,pvals_BH,fold_changes)
dot$group<-"NRP1_vs_not-treated in infected Plaque"
colnames(dot)<-c("pvalue","BH","FC","group")

dot$type_pvalue <- ifelse(dot$pvalue < 0.05, "Significant","Not Significant")#, "Not Significant")
dot$type_pvalue <- factor(dot$type_pvalue, levels = c("Significant","Not Significant"))#, "Not Significant"))

pdf(file="nrp1_point_plot_rawpvalue.pdf",height = 10,width = 8)
ggplot(dot, aes(group, rownames(dot))) +
  geom_point(aes(fill = FC, size = -log10(pvalue), color = type_pvalue, shape = type_pvalue)) + 
  scale_fill_gradientn(colours = colorRampPalette(c("#3d67a3", "white","#ce1020"))(99),
                       limits = c(-2,2), breaks = c(-2, -1, 0, 1, 2)) +
  scale_shape_manual(values = c(21,23)) +
  scale_color_manual(values = c("black","grey50","black"))+
  scale_size_continuous(breaks=c(0.5,1.5,3,4), range=c(1,4)) +
  theme_dendro() +
  theme(plot.margin = margin(1, 1, 1, 1, "cm")) +
  coord_fixed(ratio = 0.7) +
  labs(fill = "Log2 (Fold change)", size = "-Log10 (p-pvalue)", color = "", shape = "") +
  theme(axis.text.x = element_text(size = 10, face = "plain", colour = "black", angle = 45),
        axis.text.y = element_text(size = 10, face = "plain", colour = "black")) +
  theme(legend.text = element_text(size = 10, face = "plain", colour = "black"), 
        legend.title = element_text(size = 10, face = "plain", colour = "black"), 
        legend.key.height = unit(0.5, "cm"), legend.key.width = unit(0.3, "cm"))   
dev.off()
```
