---
title: "RNAseq_Covid_Plaque analysis"
date: "11/3/2022"
output: 
  html_document:
    code_folding: hide
    toc: yes
    theme: spacelab
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(DESeq2)
library(ggplot2)
library(gplots)
library(RColorBrewer)
library(pheatmap)
library(ggrepel)
library(pheatmap)
library(magrittr)
library(tidyverse)
library(ggpubr)
library(edgeR)
library(biomaRt)
```

#load DESeq object. Removed Donor 1 from the analysis
```{r}
rawcounts<-read.csv("~/DESeq/rawcounts.csv",header=T,sep=",")
sample_table<-read.csv("~/DESeq/metadata.csv")

names <- make.unique(rawcounts$Geneid)
rownames(rawcounts) <- names
rawcounts <- rawcounts[,-1] 

sample_table$Timepoint = as.factor(sample_table$Timepoint)
sample_table$Donor = as.factor(sample_table$Donor)
sample_table$Condition <- factor(sample_table$Condition, 
                              levels = c("Not_infected","SARSCov2"))

dds_cell <- DESeqDataSetFromMatrix(countData = rawcounts,
colData = sample_table,
 design = ~Timepoint+Donor)

dds_cell<-DESeq(dds_cell)
resultsNames(dds_cell)

```


## Normalized by size factor
```{r}
norm = counts(dds_cell, normalized=TRUE) 

# standardized data
x_zscore = t(scale(t(norm)))
x_zscore[is.na(x_zscore)] <- 0
```

## plot dispersion plot
```{r,fig.height=8, fig.width=8}
#pdf(file="~/EXP3_060716/dispersion_plot.pdf",height = #6,width = 6)
plotDispEsts(dds_cell)
#dev.off()
```

## plot pca 
```{r,fig.height=10, fig.width=8}
vsd <- vst(dds_cell, blind=FALSE)
#pdf(file="~/EXP3_060716/pca_plot.pdf",height = 6,width #= 6)
pcaData<-plotPCA(vsd, intgroup=c("Donor", "Condition","Timepoint"),returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
ggplot(pcaData, aes(PC1, PC2, color=as.factor(Donor), shape=Condition)) +
  geom_point(size=3) +
  geom_text_repel(size= 3.5, aes(label=as.character(Timepoint)))+
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()
#dev.off()

```

## Convert ensemble id to Gene id
```{r}
x_zscore<-as.data.frame(x_zscore)
mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
genes <- rownames(x_zscore)
genelist <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id","hgnc_symbol"),values=genes,mart= mart)
x_zscore$genes<-rownames(x_zscore)
annot <- merge(
  x = genelist,
  y = x_zscore,
  by.x="ensembl_gene_id",
  by.y="genes")
#head(annot)

zscore<-annot[,-c(1)]

names <- make.unique(zscore$hgnc_symbol)
rownames(zscore) <- names
zscore <- zscore[,-1] 

```

## Cytokines/Chemokines Heatmap
```{r,fig.height=10, fig.width=6}
cytokines<-c("IL2RA","CXCL9","CCL4","IL6","CXCL12","CCL7","IL16","IL12B","LIF","LTA","MIF","IL5",
          "TNF","CCL5","IL1B","IL18","FGF2","VEGFA","PDGFB","IL10","IL13","IL4","CCL2","CXCL8","CCL3",
          "CSF3","CXCL1","HGF","IL1A","KITLG","TNFSF10","CSF1","CCL27","IL15","IL7","IL12A","IL17A")

anno_df = data.frame(Timepoint=sample_table$Timepoint,
                    Condition=sample_table$Condition,
                    stringsAsFactors = FALSE)
anno_df$Timepoint <- as.factor(sample_table$Timepoint)
anno_df$Condition <- as.factor(sample_table$Condition)

annotation_colors = list(
  Timepoint=c("0"="#D51F26","24"="#80b1d3","48"="#fd8d3c","72"="blue2"),
    Condition=c("Not_infected"="#fd8d3c","SARSCov2"="brown4"))

rownames(anno_df) <- colnames(zscore)

zscore[zscore> 1.5] <- 1.5
zscore[zscore< -1.5] <- -1.5

pdf(file="scaled_expression_heatmap_cytokines.pdf",height=8,width=8)
pheatmap(zscore[cytokines,], fontsize_row = 9, annotation_col=anno_df, annotation_colors=annotation_colors,
           cellwidth = 9,cellheight=8,cluster_cols = F,
            main ="Cytokines",
            fontsize_col = 9)
dev.off()
```

## Entry Factors. 
```{r,fig.height=6, fig.width=6}
entry<-c("TMPRSS4", "TMPRSS2", "TMPRSS11B","TMPRSS11A", "ACE2", "NRP1", "NPR2", "CTSB", "CTSL", "FURIN")

anno_df = data.frame(Timepoint=sample_table$Timepoint,
                    stringsAsFactors = FALSE)
anno_df$Timepoint <- as.factor(sample_table$Timepoint)

annotation_colors = list(
  Timepoint=c("0"="#D51F26","24"="#80b1d3","48"="#fd8d3c","72"="blue2"))

#head(annotation_colors)
rownames(anno_df) <- colnames(zscore)

zscore[zscore> 1.5] <- 1.5
zscore[zscore< -1.5] <- -1.5

pdf(file="scaled_expression_heatmap_entryfactors.pdf",height=6,width=8)
pheatmap(zscore[entry,], fontsize_row = 9, annotation_col=anno_df, annotation_colors=annotation_colors,
           cellwidth = 9,cellheight=8,cluster_cols = F,
            main ="Entry Factors",
            fontsize_col = 9)
dev.off()
```

## Interferon response
```{r,fig.height=6, fig.width=6}
interferon<-c("JAK1", "IRF1", "IFNAR2", "IFNA1", "IFNAR1", "IRF4", "SOCS3", "IRF5", "STAT2", "MX1", "IFI35", "IRF7", "BST2", "IFITM1", "STAT1", "TYK2", "PSMB8", "PTPN6", "IFNA16", "SOCS1", "IFNA7")

anno_df = data.frame(Timepoint=sample_table$Timepoint,
                    stringsAsFactors = FALSE)
anno_df$Timepoint <- as.factor(sample_table$Timepoint)

annotation_colors = list(
  Timepoint=c("0"="#D51F26","24"="#80b1d3","48"="#fd8d3c","72"="blue2"))

rownames(anno_df) <- colnames(x_zscore)

zscore[zscore> 1.5] <- 1.5
zscore[zscore< -1.5] <- -1.5

pdf(file="scaled_expression_heatmap_interferon.pdf",height=7,width=8)
pheatmap(zscore[interferon,], fontsize_row = 9, annotation_col=anno_df, annotation_colors=annotation_colors,
           cellwidth = 9,cellheight=8,cluster_cols = F,
            main ="Interferon response",
            fontsize_col = 9)
dev.off()
```

