---
title: "Luminex_nrp1"
date: "11/14/2022"
output: 
  html_document:
    code_folding: 'hide'
    theme: yeti
    toc: false
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
library(dplyr)  
library(data.table)
library(ggplot2)
library(reshape2)
library(magrittr)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(pheatmap)
library(RColorBrewer)
library(gplots)
```

# file with clinical information of Luminex data
```{r}
data <- read.csv("~/Exp2_nrp1_ctsb/Exp2_mac_foam_treated_nrp1.csv",header=T,check.names = FALSE)

dim(data)

# Create vector containing cytokine names
name <- (names(data[,6:53]))

norm_data <- data
norm_data[name] <- log(norm_data[name]+1)
```


## NRP1 vs not treated infected
```{r}
macro<-norm_data[norm_data$Sample.ID=="Macrophages",]
macro_infected<-macro[macro$Condtion=="infected",]

nrp1_no_treatment_ttest = lapply(cytokines, function(cyto) {

	idx1 = macro_infected$Treatment == "NRP1"
	idx2 = macro_infected$Treatment == "no_treatment"

	x = macro_infected[idx1, cyto]
	y = macro_infected[idx2, cyto]
	

	x[x < 0] = 0
	y[y < 0] = 0


	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return("Failed")
})
names(nrp1_no_treatment_ttest) = cytokines

## NRP1 vs not treated infected foam cells
# NRP1 vs not treated infected
foam_infected<-foam[foam$Condtion=="infected",]

nrp1_no_treatment_ttest = lapply(cytokines, function(cyto) {

	idx1 = foam_infected$Treatment == "NRP1"
	idx2 = foam_infected$Treatment == "no_treatment"

	x = foam_infected[idx1, cyto]
	y = foam_infected[idx2, cyto]
	

	x[x < 0] = 0
	y[y < 0] = 0


	try({
		result = t.test(x, y, paired=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return("Failed")
})
names(nrp1_no_treatment_ttest) = cytokines

```

```{r}
## Statistical test on ratio between NRP1 vs not treated
ratio<-read.csv("~/Exp2_nrp1_ctsb/ratio.csv")

names <- make.unique(norm$Sample)
rownames(norm) <- names
norm <- norm[,-1] 

cytokines<-colnames(ratio)[c(-1,-2)]

nrp1<-ratio[ratio$Treatment=="NRP1_vs_nottreated",]

## mac vs foam cells
nrp1_change_ttest = lapply(cytokines, function(cyto) {

	idx1 = nrp1$Cell == "Macrophages"
	idx2 = nrp1$Cell == "Foam cells"

	x = nrp1[idx1, cyto]
	y = nrp1[idx2, cyto]
	

	x[x < 0] = 0
	y[y < 0] = 0


	try({
		result = t.test(x, y, paired=FALSE,var.equal=FALSE)
		result$estimate = c(
			mean(x, na.rm=TRUE),
			mean(y, na.rm=TRUE)
		)
		return(result)
	})
	return("Failed")
})
names(nrp1_change_ttest) = cytokines

pvals_change = data.frame(
 nrp1_change=sapply(nrp1_change_ttest, function(x) x$p.value)
)

pvals = data.frame(
  nrp1_no_treatment=sapply(nrp1_no_treatment_ttest, function(x) x$p.value),
	nrp1_foam_no_treatment=sapply(nrp1_foam_no_treatment_ttest, function(x) x$p.value)
)
pvals[is.na(pvals)] = 1.0  # conservative for missing p-values

## Define function
AdjustP <- function(x) {
    x$nrp1_mac_BH     <- p.adjust(x[,1], method = "BH")
    x$nrp1_foam_BH     <- p.adjust(x[,2], method = "BH")
    x
}
padj <- AdjustP(pvals)
padj<-padj[,-c(1:2)]

fold_changes = data.frame(
  nrp1_mac_no_treatment=sapply(nrp1_no_treatment_ttest, function(x) log2(x$estimate[1] / x$estimate[2])),
	nrp1_foam_no_treatment=sapply(nrp1_foam_no_treatment_ttest, function(x) log2(x$estimate[1] / x$estimate[2])))

rownames(fold_changes) = cytokines
fold_changes[is.na(fold_changes)] = 0.0
fold_changes[fold_changes > 10] = 10
fold_changes[fold_changes < -10] = -10


mat_mac = fold_changes
mat_mac = data.matrix(mat_mac)

notes = matrix("", nrow=nrow(mat_mac), ncol=ncol(mat_mac))
notes[padj < 0.1] = ""
notes[padj < 0.05] = "*"
notes[padj < 0.01] = "**"
notes[padj < 0.001] = "***"

noted = matrix("", nrow=nrow(mat_mac), ncol=ncol(mat_mac))
noted[pvals_change < 0.1] = ""
noted[pvals_change < 0.05] = "(*)"
noted[pvals_change < 0.01] = "(**)"
noted[pvals_change < 0.001] = "(***)"

x1<-cbind(notes,noted)

comb = data.frame(
	apply(x1,2, function(x) x)
)

data <- comb %>%
  unite("NRP1_MAC", X1,sep= " ",
        remove = FALSE) %>%
  unite(
        "NRP1_FOAM", X2,X3, sep= " ",
        remove = FALSE)


notes_f<-data[,-c(2,4:6)]
```

## Foldchange heatmap 
```{r,fig.height=10,fig.width=8}
pdf(file="Fig4H_foldchange_heatmap_mac_Foamcells_NRP1_nottreated_change_ordered_06122023.pdf",height = 10,width = 8)
heatmap.2(mat_mac,
	Colv=FALSE,
	Rowv = FALSE,
	mar=c(10, 30),
	trace="none",
	# col=colorRampPalette(rev(brewer.pal(9, "RdBu")))(100)
	breaks=seq(-1,1, length.out=101),
	col=colorRampPalette(rev(brewer.pal(9, "Spectral")))(100),
	key.xlab=expression("log"[2] * " FC"), key.ylab=NA,
	key.title="",
	cellnote=notes_f,
	notecol="black",
	cexCol=1
)
dev.off()
```

## z-score heatmap for MAC
```{r}
# mean
release = data[,6:ncol(data)]  # main data matrix
rownames(release) = data$Sample.ID

# Cytokine release data
release_zscore = scale(release)
release_zscore[is.na(release_zscore)] = 0.0

not_infected_means = apply(release_zscore[data$`Sample ID` == "Macrophages" & data$Condtion == "not infected" & data$Treatment == "no_treatment",], 2, mean, na.rm=TRUE)
infected_means = apply(release_zscore[data$`Sample ID` == "Macrophages" & data$Condtion == "infected" & data$Treatment == "no_treatment",], 2, mean, na.rm=TRUE)
nrp1_means = apply(release_zscore[data$`Sample ID` == "Macrophages" & data$Condtion == "infected" & data$Treatment == "NRP1",], 2, mean, na.rm=TRUE)

heat<-data.frame(not_infected_means,infected_means,nrp1_means)
heat<-t(heat)

Condition<-c("not infected","infected","infected")
Treatment<-c("not_treatment","not_treatment","NRP1")

heat_final<-cbind(heat,Condition,Treatment)
heat_final<-as.data.frame(heat_final)

anno_df = data.frame(Condition=as.factor(heat_final$Condition),
                     Treatment=as.factor(heat_final$Treatment),
                    stringsAsFactors = FALSE)

annotation_colors = list(
  Condition=c("not infected"="#4DAF4A","infected"="#984EA3"),
  Treatment=c("not_treatment"="#377EB8","NRP1"="#E41A1C"))

#head(annotation_colors)
rownames(anno_df) <- rownames(heat)

heat[heat > 1.5] <- 1.5
heat[heat < -1.5] <- -1.5

pdf(file="MAC_average_exp.pdf",height = 10,width = 8)
pheatmap(t(heat),annotation_col=anno_df, annotation_colors=annotation_colors,
               fontsize_row = 10, cellwidth = 10,cellheight=10,cluster_cols = F,
               main="Mac averaged zscore",
               legend_breaks = c(-1.5,-1,-0.5, 0, 0.5,1,1.5, max(t(heat))),
               legend_labels=c("-1.5","-1","-0.5", "0", "0.5","1","1.5", "zscore\n"),
               cluster_rows=F,
               fontsize_col = 10)
dev.off()

# mean for foam cells
release = data[,6:ncol(data)]  # main data matrix
rownames(release) = data$Sample.ID

# Cytokine release data
release_zscore = scale(release)
release_zscore[is.na(release_zscore)] = 0.0

not_infected_means = apply(release_zscore[data$`Sample ID` == "Foam cells" & data$Condtion == "not infected" & data$Treatment == "no_treatment",], 2, mean, na.rm=TRUE)
infected_means = apply(release_zscore[data$`Sample ID` == "Foam cells" & data$Condtion == "infected" & data$Treatment == "no_treatment",], 2, mean, na.rm=TRUE)
nrp1_means = apply(release_zscore[data$`Sample ID` == "Foam cells" & data$Condtion == "infected" & data$Treatment == "NRP1",], 2, mean, na.rm=TRUE)

heat<-data.frame(not_infected_means,infected_means,nrp1_means)
heat<-t(heat)

Condition<-c("not infected","infected","infected")
Treatment<-c("not_treatment","not_treatment","NRP1")

heat_final<-cbind(heat,Condition,Treatment)
heat_final<-as.data.frame(heat_final)

anno_df = data.frame(Condition=as.factor(heat_final$Condition),
                     Treatment=as.factor(heat_final$Treatment),
                    stringsAsFactors = FALSE)

annotation_colors = list(
  Condition=c("not infected"="#4DAF4A","infected"="#984EA3"),
  Treatment=c("not_treatment"="#377EB8","NRP1"="#E41A1C"))

#head(annotation_colors)
rownames(anno_df) <- rownames(heat)

heat[heat > 1.5] <- 1.5
heat[heat < -1.5] <- -1.5

pdf(file="FOAM_average_exp.pdf",height = 10,width = 8)
pheatmap(t(heat),annotation_col=anno_df, annotation_colors=annotation_colors,
               fontsize_row = 10, cellwidth = 10,cellheight=10,cluster_cols = F,
               main="Foam cells averaged zscore",
               legend_breaks = c(-1.5,-1,-0.5, 0, 0.5,1,1.5, max(t(heat))),
               legend_labels=c("-1.5","-1","-0.5", "0", "0.5","1","1.5", "zscore\n"),
               cluster_rows=F,
               fontsize_col = 10)
dev.off()

```